Repository COS301-SE-2022/Tutor-Me, pull requests merged in 2022-06, with the labels that each got.

#57 💄 Updated UI elements
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/src/ImageUpload/image_picker.dart
  lib/src/Search/search_bar.dart
  lib/src/app.dart
  lib/src/pages/calls_page.dart
  lib/src/pages/chat_page.dart
  lib/src/pages/tutees_list.dart
  lib/src/tutee_page.dart
  lib/src/tutor_page.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: frontend

#58 💄 Fixed UI links
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutor_page.dart
Labels: frontend

#67 Added profile edit.
  assets/Pictures/avatar.jpeg
  lib/main.dart
  lib/src/chat/chat.dart
  lib/src/chat/message.dart
  lib/src/pages/chat_page.dart
  lib/src/pages/chats_page.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutor_page.dart
Labels: frontend

#68 💄 (UI) Tutee Profile edits
  assets/Pictures/tuteeCover.jpg
  assets/Pictures/tuteeProfile.jpg
  lib/main.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend, High

#70 💄 Added new UI to pages
  lib/src/pages/chats_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/tutee_page.dart
Labels: frontend

#71 🚧(BE & FE)Connect backend with updated FE
  lib/modules/api.services.dart
  lib/services/models/tutees.dart
  lib/services/models/tutors.dart
  lib/services/tutee_services.dart
  lib/services/tutor_services.dart
  lib/src/pages/tutors_list.dart
  lib/src/tutee_page.dart
  pubspec.lock
  web/Api/Api/obj/Debug/net6.0/Api.GeneratedMSBuildEditorConfig.editorconfig
  web/Api/Api/obj/Debug/net6.0/Api.assets.cache
  web/Api/Api/obj/Debug/net6.0/project.razor.json
  windows/flutter/generated_plugins.cmake
Labels: backend, frontend, High

#76 ✨ (search): Added Search Functionality
  lib/src/pages/tutors_list.dart
Labels: enhancement, backend, frontend, Database, Medium, API

#78 Create dotnet.yml
  .github/workflows/dotnet.yml
  .github/workflows/flutter.yml
Labels: tests, High

#79 ✅ (Unit test) : added GetTutor ReturnFound
  web/Api/Api.sln.DotSettings.user
  web/Api/Api/obj/Debug/net6.0/Api.GeneratedMSBuildEditorConfig.editorconfig
  web/Api/Api/obj/Debug/net6.0/project.razor.json
  web/Api/Api/obj/staticwebassets.pack.sentinel
  web/Api/ApiUnitTests/UnitTests.cs
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.csproj.AssemblyReference.cache
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/Debug/net6.0/ref/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/refint/ApiUnitTests.dll
Labels: tests, Medium, API

#81 ✨ (Video Call): Added Video Call Functionality
  .env
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/constants/colors.dart
  lib/main.dart
  lib/navigator_key.dart
  lib/screens/chat_screen.dart
  lib/screens/join_screen.dart
  lib/screens/meeting_screen.dart
  lib/screens/splash_screen.dart
  lib/screens/startup_screen.dart
  lib/src/pages/calls_page.dart
  lib/utils/spacer.dart
  lib/utils/toast.dart
  lib/widgets/chat/chat_widget.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
  lib/widgets/meeting_controls/meeting_action_button.dart
  lib/widgets/participant_grid_view/participant_grid_view.dart
  lib/widgets/participant_grid_view/participant_tile.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, frontend, Medium

#83 ✨ (Chat in Video call)
  lib/screens/meeting_screen.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
Labels: enhancement, good first issue, frontend, Medium

#86 💄 (UI) Updated UI
  lib/src/components.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  pubspec.yaml
  windows/flutter/generated_plugins.cmake
Labels: enhancement, frontend

#91 💄 (Frontend): Added and fixed search functionality
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
Labels: frontend, High

#94 💄 (Frontend): refined module editing
  lib/src/Modules/module.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#95 🚧 (Backend): add register tutor
  lib/services/models/tutors.dart
  lib/services/services/tutor_services.dart
  lib/src/pages/tutors_list.dart
Labels: backend

#98 🚀 (Backend): get modules for a specific user
  lib/services/services/tutor_services.dart
Labels: backend

#100 Simphiwe
  web/Api/Api/bin/Debug/net6.0/Api.dll
  web/Api/Api/bin/Debug/net6.0/Api.pdb
  web/Api/Api/obj/Api.csproj.nuget.dgspec.json
  web/Api/Api/obj/Api.csproj.nuget.g.props
  web/Api/Api/obj/Api.csproj.nuget.g.targets
  web/Api/Api/obj/Debug/net6.0/Api.csproj.CoreCompileInputs.cache
  web/Api/Api/obj/Debug/net6.0/Api.dll
  web/Api/Api/obj/Debug/net6.0/Api.pdb
  web/Api/Api/obj/Debug/net6.0/project.razor.json
  web/Api/Api/obj/Debug/net6.0/ref/Api.dll
  web/Api/Api/obj/Debug/net6.0/refint/Api.dll
  web/Api/Api/obj/project.assets.json
  web/Api/Api/obj/project.nuget.cache
  web/Api/Api/obj/staticwebassets.pack.sentinel
  web/Api/ApiUnitTests/UnitTests.cs
  web/Api/ApiUnitTests/bin/Debug/net6.0/Api.dll
  web/Api/ApiUnitTests/bin/Debug/net6.0/Api.pdb
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/ApiUnitTests.csproj.nuget.dgspec.json
  web/Api/ApiUnitTests/obj/ApiUnitTests.csproj.nuget.g.props
  web/Api/ApiUnitTests/obj/ApiUnitTests.csproj.nuget.g.targets
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.csproj.AssemblyReference.cache
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/Debug/net6.0/ref/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/refint/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/project.assets.json
  web/Api/ApiUnitTests/obj/project.nuget.cache
Labels: tests, Medium, API

#102 🐛 (fix tutor class types)
  lib/services/models/tutors.dart
  lib/services/services/tutor_services.dart
Labels: backend

#105 Simphiwe
  web/Api/Api/obj/staticwebassets.pack.sentinel
  web/Api/ApiUnitTests/UnitTests.cs
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.pdb
  web/Api/ApiUnitTests/obj/Debug/net6.0/ref/ApiUnitTests.dll
  web/Api/ApiUnitTests/obj/Debug/net6.0/refint/ApiUnitTests.dll
Labels: tests, Medium, API

#106 ✅ (unit test): added tutee unit tests
  web/Api/ApiUnitTests/TutorUnitTests.cs
  web/Api/ApiUnitTests/TutteeUnitTests.cs
Labels: tests, Medium, API

#113 🚧 (backend):tutors set age
  lib/services/models/tutors.dart
Labels: backend

#112 🐛 fixed login and register
  lib/main.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register.dart
  lib/src/authenticate/register_or_login.dart
  lib/src/colorpallete.dart
  lib/src/components.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  pubspec.lock
Labels: bug, frontend

#116 💄 (Frontend): Added filter functionlity
  lib/src/pages/tutors_list.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
Labels: frontend, High

#117 💄 Updated UI (Register and Login)
  lib/src/authenticate/register.dart
  pubspec.lock
  windows/flutter/generated_plugins.cmake
Labels: frontend

#120 💄(UI) updated
  lib/src/authenticate/register.dart
Labels: enhancement, frontend

#121 🚧 (Register tutor and tutee): hash passwords
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  pubspec.yaml
Labels: backend

#123 Fixed Profiles and profile view
  lib/src/chat/chat.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/tutees_list.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_data.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
  lib/src/tutor_page.dart
Labels: frontend, Low

#122 ✨ (UI)Validate user inputs on Register and Login
  lib/services/services/tutor_services.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register.dart
  lib/src/colorpallete.dart
  lib/src/components.dart
Labels: enhancement, frontend

#124 💄 (FrontEnd): UI changes
  assets/Pictures/penguin.png
  lib/main.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend

#126 Simphiwe
  web/Api/ApiUnitTests/TutorUnitTests.cs
  web/Api/ApiUnitTests/TutteeUnitTests.cs
Labels: tests, backend, Medium, API

#128 🚧 (Backend): Upload tutee Profile picture to database
  lib/services/services/tutee_services.dart
Labels: backend

#130 🚨 remove rating from tutee service
  lib/main.dart
  lib/services/services/tutor_services.dart
Labels: enhancement, backend

#127 UI Changes
  lib/main.dart
  lib/services/models/tutees.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register.dart
  lib/src/chat/chat.dart
  lib/src/components.dart
  lib/src/pages/chats_page.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/edit_tutee_profile_page.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutor_page.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend
