Repository COS301-SE-2022/Tutor-Me, pull requests merged in 2022-07, with the labels that each got.

#132 ✨ (Video Call): Added Video Call Functionality
  .env
  .gitignore
  lib/main.dart
  lib/screens/chat_screen.dart
  lib/screens/join_screen.dart
  lib/screens/meeting_screen.dart
  lib/screens/splash_screen.dart
  lib/screens/startup_screen.dart
  lib/src/pages/calls_page.dart
  lib/utils/spacer.dart
  lib/utils/toast.dart
  lib/widgets/chat/chat_widget.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
  lib/widgets/meeting_controls/meeting_action_button.dart
  lib/widgets/participant_grid_view/participant_grid_view.dart
  lib/widgets/participant_grid_view/participant_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, backend, frontend, Medium, API

#139 ✨ 🍱 (enhance): Decorate Meeting Screen
  assets/Pictures/teacher.png
  assets/Pictures/teacher1.png
  lib/screens/meeting_screen.dart
  lib/src/authenticate/login.dart
Labels: enhancement, frontend, Low

#145 🚧 (FrontEnd): return a list of user requests
  APIs/FileSystemAPI/.vs/FileSystem/v17/.futdcache.v1
  APIs/FileSystemAPI/.vs/FileSystem/v17/.suo
  APIs/FileSystemAPI/.vs/ProjectEvaluation/filesystem.metadata.v2
  APIs/FileSystemAPI/.vs/ProjectEvaluation/filesystem.projects.v2
  lib/main.dart
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
Labels: backend, frontend

#149 UI Changes
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/notifications/tutor_notifications.dart
  lib/src/notifications/tutors_activity.dart
  lib/src/notifications/tutors_requests.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/tutee_page.dart
  lib/src/tutor_page.dart
Labels: frontend, Medium

#151 🩹(End call): Leaving call takes you to first page
  lib/screens/meeting_screen.dart
  lib/src/authenticate/login.dart
Labels: enhancement, frontend, Low

#169 🐛 Fetched data from the api
  .vscode/settings.json
  lib/src/authenticate/register_step1.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
Labels: enhancement, frontend, API

#175 ✨(search email): check if email exists before registration
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register_step1.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
Labels: enhancement, backend, frontend, Medium, API

#179 🐛 ✨ (Fix Toggle Switch): stay in correct state
  lib/src/authenticate/forgot_password.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register_step1.dart
  windows/flutter/generated_plugins.cmake
Labels: bug, enhancement, frontend, Medium

#185 💄(frontend): Add tutor rating system
  lib/src/pages/chats_page.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
Labels: frontend, Medium

#188 Simphiwe
  APIs/TutorMeApi/ApiIntegrationTests/ModuleControllerIntegrationTests.cs
  APIs/TutorMeApi/ApiIntegrationTests/TuteeControllerIntegrationTests.cs
  APIs/TutorMeApi/ApiIntegrationTests/TutorControllerIntegrationTests.cs
  APIs/TutorMeApi/ApiUnitTests/RequestUnitTests.cs
Labels: tests, backend, Database, Medium, API

#192 ✨ (Add UI): Gridview for Admin
  assets/Pictures/deleteModule.png
  assets/Pictures/deleteTutee.png
  assets/Pictures/deleteTutor.png
  assets/Pictures/settings.png
  assets/Pictures/update.png
  lib/src/admin/admin.dart
  lib/src/admin/admin_home.dart
  lib/src/admin/delete_module.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
  lib/src/authenticate/register_or_login.dart
  pubspec.yaml
Labels: enhancement, frontend, Medium

#194 🐛(fix UI): responsiveness of gridview on different screen sizes
  lib/src/admin/admin.dart
Labels: enhancement, frontend, Medium

#197 (bug): accept request: saving incorrect data
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.assets.cache
  APIs/FileSystemAPI/FileSystemUnitTests/obj/Debug/net6.0/FileSystemUnitTests.assets.cache
  lib/services/services/tutor_services.dart
Labels: frontend

#195 fixed bug on tutor list and tutor rating
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend

#199 👔 (FrontEnd): add course to register parameter
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  lib/src/authenticate/register_step3.dart
Labels: frontend

#205 Created the groupChat UI
  lib/src/Groups/group.dart
  lib/src/Groups/tutor_group.dart
Labels: frontend, Medium

#203 ✨ (Admin): Admin interface
  assets/Pictures/Admin.jpg
  lib/src/admin/login.dart
  lib/src/authenticate/register_or_login.dart
Labels: enhancement, frontend, Low

#212 cater for API host changes
  .gitignore
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.assets.cache
  APIs/FileSystemAPI/FileSystemUnitTests/obj/Debug/net6.0/FileSystemUnitTests.assets.cache
  APIs/TutorMeApi/.vs/Api/FileContentIndex/1202cc51-877f-4373-a590-f4cd18a67670.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/23e19f4a-c8ba-4dab-991c-f7e123c79fcc.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/74b13ce4-0305-4d2a-a3f4-f97f98b28611.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/85415ce6-8f3d-4b66-b0d0-5a68ff6e74d9.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/b9a7c2e3-182f-45e1-85a2-4161545d5ca5.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/c94d1de3-9ed9-4809-8394-dfe4e7d048d5.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/decdccae-96eb-4209-abec-a3ff1322f404.vsidx
  APIs/TutorMeApi/.vs/Api/FileContentIndex/f7a98116-fe61-468d-b7cb-dc23e5fe22ce.vsidx
  APIs/TutorMeApi/.vs/Api/v17/.suo
  APIs/TutorMeApi/.vs/ProjectEvaluation/api.projects.v2
  APIs/TutorMeApi/Api/Api.csproj.user
  APIs/TutorMeApi/Api/Properties/PublishProfiles/TutorMe - Web Deploy.pubxml
  APIs/TutorMeApi/Api/Properties/PublishProfiles/TutorMe - Web Deploy.pubxml.user
  APIs/TutorMeApi/Api/Properties/ServiceDependencies/TutorMe - Web Deploy/profile.arm.json
  APIs/TutorMeApi/Api/bin/Release/net6.0/Api.dll
  APIs/TutorMeApi/Api/bin/Release/net6.0/Api.pdb
  APIs/TutorMeApi/Api/obj/Api.csproj.nuget.dgspec.json
  APIs/TutorMeApi/Api/obj/Api.csproj.nuget.g.props
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.assets.cache
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.csproj.AssemblyReference.cache
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.csproj.CoreCompileInputs.cache
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.csproj.FileListAbsolute.txt
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.dll
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.genruntimeconfig.cache
  APIs/TutorMeApi/Api/obj/Release/net6.0/Api.pdb
  APIs/TutorMeApi/Api/obj/Release/net6.0/PubTmp/Api.Parameters.xml
  APIs/TutorMeApi/Api/obj/Release/net6.0/PubTmp/Api.SourceManifest.xml
  APIs/TutorMeApi/Api/obj/Release/net6.0/PubTmp/Out/Api.dll
  APIs/TutorMeApi/Api/obj/Release/net6.0/PubTmp/Out/Api.pdb
  APIs/TutorMeApi/Api/obj/Release/net6.0/PublishOutputs.260b691e97.txt
  APIs/TutorMeApi/Api/obj/project.assets.json
  APIs/TutorMeApi/Api/obj/project.nuget.cache
  APIs/TutorMeApi/Api/obj/staticwebassets.pack.sentinel
  APIs/TutorMeApi/ApiIntegrationTests/bin/Release/net6.0/CoverletSourceRootsMapping
  APIs/TutorMeApi/ApiIntegrationTests/obj/ApiIntegrationTests.csproj.nuget.dgspec.json
  APIs/TutorMeApi/ApiIntegrationTests/obj/ApiIntegrationTests.csproj.nuget.g.props
  APIs/TutorMeApi/ApiIntegrationTests/obj/Release/net6.0/ApiIntegrationTests.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMeApi/ApiIntegrationTests/obj/Release/net6.0/ApiIntegrationTests.assets.cache
  APIs/TutorMeApi/ApiIntegrationTests/obj/Release/net6.0/ApiIntegrationTests.csproj.AssemblyReference.cache
  APIs/TutorMeApi/ApiIntegrationTests/obj/project.assets.json
  APIs/TutorMeApi/ApiIntegrationTests/obj/project.nuget.cache
  APIs/TutorMeApi/ApiUnitTests/bin/Release/net6.0/CoverletSourceRootsMapping
  APIs/TutorMeApi/ApiUnitTests/obj/ApiUnitTests.csproj.nuget.dgspec.json
  APIs/TutorMeApi/ApiUnitTests/obj/ApiUnitTests.csproj.nuget.g.props
  APIs/TutorMeApi/ApiUnitTests/obj/Release/net6.0/ApiUnitTests.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMeApi/ApiUnitTests/obj/Release/net6.0/ApiUnitTests.assets.cache
  APIs/TutorMeApi/ApiUnitTests/obj/Release/net6.0/ApiUnitTests.csproj.AssemblyReference.cache
  APIs/TutorMeApi/ApiUnitTests/obj/project.assets.json
  APIs/TutorMeApi/ApiUnitTests/obj/project.nuget.cache
  lib/services/services/module_services.dart
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  windows/flutter/generated_plugins.cmake
Labels: backend, frontend, High, API

#217 ✨ (group chat UI): frontend with mock data
  lib/src/chat/chat.dart
  lib/src/chat/group_chat.dart
  lib/src/chat/message.dart
  pubspec.yaml
Labels: enhancement, good first issue, frontend, Medium

#219 👽️ : change files api host to aws
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
Labels: backend, Database, API

#226 ✨(Admin Login): with hashed password
  lib/services/models/admins.dart
  lib/services/services/admin_services.dart
  lib/src/admin/admin_home.dart
  lib/src/admin/login.dart
Labels: backend, Database, Medium, API

#231 🌱 added GroupModel and Groups services functions
  lib/services/models/groups.dart
  lib/services/services/group_services.dart
Labels: frontend, High

#230 ✨ (Admin): Delete Tutor, Tutee or Module
  lib/services/services/module_services.dart
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
Labels: enhancement, backend, Database, Medium, API

#232 Adding and refining UI elements
  lib/services/services/tutor_services.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Modules/module.dart
  lib/src/chat/chat.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend

#236 Frontend: Added image display
  lib/services/services/tutee_services.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
  lib/src/tutor_page.dart
Labels: frontend, High

#237 Fixed a bug
  lib/src/pages/tutors_list.dart
Labels: frontend

#238 🏷️ (Frontend): Added getGroupById function
  lib/services/services/group_services.dart
Labels: frontend

#240 Update tutor_services request url
  lib/services/services/tutor_services.dart
Labels: frontend

#242 🐛 (FrontEnd) : Fixed a bug
  lib/src/Groups/tutor_group.dart
Labels: frontend

#241 💄 (UI) Integrate Group Pages with API
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.assets.cache
  APIs/FileSystemAPI/FileSystemUnitTests/obj/Debug/net6.0/FileSystemUnitTests.assets.cache
  APIs/TutorMeApi/Api/bin/Debug/net6.0/Api
  APIs/TutorMeApi/Api/bin/Debug/net6.0/Api.dll
  APIs/TutorMeApi/Api/bin/Debug/net6.0/Api.pdb
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.assets.cache
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.csproj.CoreCompileInputs.cache
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.dll
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.genruntimeconfig.cache
  APIs/TutorMeApi/Api/obj/Debug/net6.0/Api.pdb
  APIs/TutorMeApi/Api/obj/Debug/net6.0/apphost
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/Api
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/Api.dll
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/Api.pdb
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.dll
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/ApiUnitTests.pdb
  APIs/TutorMeApi/ApiUnitTests/bin/Debug/net6.0/CoverletSourceRootsMapping
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.assets.cache
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.csproj.AssemblyReference.cache
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.csproj.CoreCompileInputs.cache
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.dll
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.genruntimeconfig.cache
  APIs/TutorMeApi/ApiUnitTests/obj/Debug/net6.0/ApiUnitTests.pdb
  assets/Pictures/artificialintelligence.jpg
  lib/main.dart
  lib/src/Groups/group.dart
  lib/src/Groups/tutee_group.dart
  lib/src/authenticate/login.dart
  lib/src/colorpallete.dart
  lib/src/services/models/modules.dart
  lib/src/services/services/tutee_services.dart
  lib/src/tuteeProfilePages/edit_modules.dart
  lib/src/tuteeProfilePages/edit_tutee_profile_page.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tuteeGroupSettings.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tuteeGroups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/participantslist.dart
  windows/flutter/generated_plugins.cmake
Labels: enhancement, backend, frontend, API

#243 💄 (Frontend): Updated request functionality
  lib/services/models/requests.dart
  lib/services/services/tutor_services.dart
  lib/src/authenticate/login.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend, High

#246 🩹 circular progress indicator
  assets/Technical installation manual.pdf
  lib/main.dart
  lib/src/admin/login.dart
  lib/src/authenticate/register_step3.dart
Labels: bug, Low

#250 Farai
  lib/src/authenticate/register_step2.dart
Labels: enhancement, frontend, Medium

#251 🐛 (fix a bug): hashed the forgot password
  lib/src/authenticate/change_password.dart
Labels: bug, frontend, High

#254 Refined UI elements
  lib/src/Groups/group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/components.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutorGroups.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
Labels: frontend

#253 ✨ (Verify Email): On Register
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-night-hdpi/splash.png
  android/app/src/main/res/drawable-night-mdpi/splash.png
  android/app/src/main/res/drawable-night-xhdpi/splash.png
  android/app/src/main/res/drawable-night-xxhdpi/splash.png
  android/app/src/main/res/drawable-night-xxxhdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  lib/src/authenticate/register_step1.dart
Labels: enhancement, backend, frontend, Medium

#247 ✨ 💄(UI,Integration) Designed and integrated groups apage tutor participant
  lib/src/Groups/tutee_group.dart
  lib/src/authenticate/login.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_data.dart
  lib/src/tutee_page.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutor_page.dart
Labels: enhancement, frontend, API

#256 UI Updates
  lib/src/chat/group_chat.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#257 Updated chat interface.
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/chat/chat.dart
  lib/src/chat/group_chat.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/pages/chats_page.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
Labels: frontend, Medium

#266 Fixed the video calling interface
  lib/services/services/group_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend, High

#267 🐛 Fixed a bug
  lib/src/Groups/tutee_group.dart
Labels: frontend

#270 Made UI changes and bug fixes
  assets/Pictures/onlineLesson.jpg
  assets/Pictures/technology.jpg
  lib/services/services/group_services.dart
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  lib/src/authenticate/register_step1.dart
  lib/src/landingPages/landing_page.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  pubspec.yaml
Labels: frontend, High

#273 Updated Theme UI
  lib/src/Groups/tutee_group.dart
  lib/src/Navigation/switch_change_theme.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/colorpallete.dart
  lib/src/settings/settings_service.dart
  lib/src/theme/themes.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
  windows/flutter/generated_plugins.cmake
Labels: enhancement, API

#274 Fixed Bug
  lib/src/Navigation/switch_change_theme.dart
  lib/src/theme/themes.dart
Labels: enhancement, frontend
