Repository COS301-SE-2022/Tutor-Me, pull requests merged in 2022-05, with the labels that each got.

#19 💄(UI) : added UI interface for tutee profile
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#22 💄 Added UI for nav Drawer and profile pages
  lib/src/Navigation/nav_drawer.dart
  lib/src/tuteeProfilePages/edit_modules.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#21 💄 (UI update): update main.dart and app.dart
  lib/main.dart
  lib/src/app.dart
Labels: frontend

#23 ✅ (Update pubspec): Add assets
  pubspec.yaml
Labels: frontend

#24 💄 (Added UI Styles): added cross page communication
  lib/main.dart
  lib/src/app.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: enhancement, frontend

#29 Removed unused import
  test/widget_test.dart
Labels: tests

#32 💄 Updated the UI
  lib/src/Navigation/nav_drawer.dart
  lib/src/app.dart
  lib/src/tuteeProfilePages/edit_tutee_profile_page.dart
  lib/src/tuteeProfilePages/tutee_data.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#33 Simphiwe
  test/widget_test.dart
Labels: tests, frontend

#35 💄 Update UI elements
  lib/src/app.dart
  lib/src/tuteeProfilePages/edit_modules.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend

#37 ✅ (widget testing) : adding widget testing
  test/widget_test.dart
Labels: tests

#36 🚧 🏗️ (API and Backend): Start Building the Tutor Web API, initial build and initializing backend
  lib/modules/api.services.dart
  lib/modules/tutors.dart
  pubspec.lock
  pubspec.yaml
Labels: backend

#39 💄 Added UI element
  lib/src/tuteeProfilePages/tutee_data.dart
Labels: frontend

#38 👽️ API changes and UI
  lib/src/app.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: frontend

#40 💄 Added Themes
  lib/src/app.dart
  lib/src/theme/themes.dart
Labels: enhancement, frontend

#41 Updated UI for register and login
  assets/Pictures/background.jpg
  assets/Pictures/student.jpg
  assets/Pictures/tutor.jpg
  lib/main.dart
  lib/src/authenticate/register.dart
  lib/src/authenticate/register_or_login.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
Labels: frontend
