Repository COS301-SE-2022/Tutor-Me, pull requests merged in 2022-09, with the labels that each got.

#332 (FE-BE integrations) Modified services files
  lib/main.dart
  lib/services/models/groups.dart
  lib/services/services/group_services.dart
  lib/services/services/module_services.dart
  lib/services/services/user_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/models/event.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/calendar.dart
  lib/src/pages/chat_page.dart
  lib/src/pages/home.dart
  lib/src/pages/inviteToMeeting.dart
  lib/src/tuteeProfilePages/add_modules.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tutee_page.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  pubspec.yaml
Labels: enhancement, frontend, High, API

#333 ✨ Forgot Password
  lib/services/services/user_services.dart
  lib/src/authenticate/change_password.dart
Labels: enhancement, backend, frontend, API

#337 Fixed more services
  assets/Pictures/undraw_account_re_o7id.svg
  assets/Pictures/undraw_maker_launch_re_rq81.svg
  assets/Pictures/undraw_online_connection_6778.svg
  assets/Pictures/undraw_visionary_technology_re_jfp7.svg
  lib/services/models/user_modules.dart
  lib/services/services/group_services.dart
  lib/services/services/module_services.dart
  lib/services/services/tutee_services.dart
  lib/services/services/user_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register_step1.dart
  lib/src/colorpallete.dart
  lib/src/landingPages/landing_page.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutor_page.dart
Labels: frontend, High

#338 ✨ (Video Call): add recording button
  assets/Pictures/recording.png
  lib/screens/meeting_screen.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
Labels: backend, frontend, Low, API

#339 Added screens and Functionalities, badges and calendar
  assets/Pictures/badges/reg.png
  assets/Pictures/profileBackground.jpg
  assets/Pictures/progressBar.jpg
  assets/Pictures/reg.png
  lib/src/Groups/tutee_group.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/colorpallete.dart
  lib/src/models/event.dart
  lib/src/pages/badges.dart
  lib/src/pages/book_for_tutor.dart
  lib/src/pages/booking_calendar.dart
  lib/src/pages/calendar.dart
  lib/src/pages/calendarScreen.dart
  lib/src/pages/home.dart
  lib/src/pages/inviteToMeeting.dart
  lib/src/pages/tutor_explore.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/pages/upcoming.dart
  lib/src/tutee_page.dart
  lib/src/tutor_page.dart
Labels: enhancement, frontend

#341 🐛 (Chat) localhost chat
  APIs/TutorMeChatAPI/Chat application server/Properties/launchSettings.json
  lib/src/pages/chat_page.dart
Labels: enhancement, backend, frontend, High, API

#344 💄 Admin UI
  .env
  android/gradle.properties
  assets/Pictures/Admin_Background.jpg
  lib/screens/recording_screen.dart
  lib/src/admin/delete_module.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/login.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
  pubspec.yaml
Labels: enhancement, backend, frontend, Database, Medium, API

#345 (UI) Impemented a recorded videos screen
  assets/Pictures/video.jpg
  lib/main.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/authenticate/register_step1.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
  lib/src/pages/booking_calendar.dart
  lib/src/pages/calendar.dart
  lib/src/pages/calendar_screen.dart
  lib/src/pages/invite_to_meeting.dart
  lib/src/pages/recorded_videos.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
Labels: enhancement, frontend

#357 (API): authenticate endpoints
  APIs/TutorMe/.vs/TutorMe/FileContentIndex/1c2d0679-2546-4b18-8ff2-a76fae7e5638.vsidx
  APIs/TutorMe/.vs/TutorMe/FileContentIndex/4dffeb98-f755-4a68-801a-4d6b5c69000f.vsidx
  APIs/TutorMe/.vs/TutorMe/FileContentIndex/5ebd0559-b21c-420c-ad75-7aae7fb4763a.vsidx
  APIs/TutorMe/.vs/TutorMe/FileContentIndex/6e8748d7-c3e6-412f-ab52-ad5cc4e353d0.vsidx
  APIs/TutorMe/.vs/TutorMe/v17/.suo
  APIs/TutorMe/TutorMe/Controllers/ConnectionsController.cs
  APIs/TutorMe/TutorMe/Controllers/GroupsController.cs
  APIs/TutorMe/TutorMe/Controllers/InstitutionsController.cs
  APIs/TutorMe/TutorMe/Controllers/ModulesController.cs
  APIs/TutorMe/TutorMe/Controllers/RequestsController.cs
  APIs/TutorMe/TutorMe/Controllers/UserModulesController.cs
  APIs/TutorMe/TutorMe/Controllers/UserTypesController.cs
  APIs/TutorMe/TutorMe/Controllers/UsersController.cs
  APIs/TutorMe/TutorMe/bin/Debug/net6.0/TutorMe.deps.json
  APIs/TutorMe/TutorMe/bin/Debug/net6.0/TutorMe.dll
  APIs/TutorMe/TutorMe/bin/Debug/net6.0/TutorMe.pdb
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.GeneratedMSBuildEditorConfig.editorconfig
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.MvcApplicationPartsAssemblyInfo.cs
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.assets.cache
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.csproj.CoreCompileInputs.cache
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.genruntimeconfig.cache
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.pdb
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/apphost
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/ref/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/refint/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/TutorMe.csproj.nuget.dgspec.json
  APIs/TutorMe/TutorMe/obj/TutorMe.csproj.nuget.g.props
  APIs/TutorMe/TutorMe/obj/TutorMe.csproj.nuget.g.targets
  APIs/TutorMe/TutorMe/obj/project.assets.json
  APIs/TutorMe/TutorMe/obj/project.nuget.cache
  APIs/TutorMe/TutorMe/obj/staticwebassets.pack.sentinel
  lib/src/pages/chat_page.dart
Labels: backend, Database, API

#360 ✨(Backend) New features on group Chat
  APIs/TutorMeChatAPI/Chat application server/Hubs/ChatHub.cs
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/change_password.dart
  lib/src/authenticate/forgot_password.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/otp.dart
  lib/src/authenticate/register_step1.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/colorpallete.dart
  lib/src/components.dart
  lib/src/landingPages/landing_page.dart
  lib/src/models/event.dart
  lib/src/notifications/tuteeNotifications/tutee_activity.dart
  lib/src/notifications/tuteeNotifications/tutee_pending_requests.dart
  lib/src/notifications/tutorNotifications/tutors_activity.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/badges.dart
  lib/src/pages/book_for_tutor.dart
  lib/src/pages/booking_calendar.dart
  lib/src/pages/calendar.dart
  lib/src/pages/calendar_screen.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/home.dart
  lib/src/pages/invite_to_meeting.dart
  lib/src/pages/recorded_videos.dart
  lib/src/pages/report_a_peer.dart
  lib/src/pages/tutor_explore.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/pages/upcoming.dart
  lib/src/tuteeProfilePages/add_modules.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutee_page.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tuteeGroupSettings.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
  lib/src/tutor_page.dart
Labels: enhancement, backend, High

#362 Added tokens to api headers
  lib/services/services/admin_services.dart
  lib/services/services/group_services.dart
  lib/services/services/institution_services.dart
  lib/services/services/module_services.dart
  lib/services/services/tutee_services.dart
  lib/services/services/tutor_services.dart
  lib/services/services/user_services.dart
  lib/services/services/users.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/admin/admin.dart
  lib/src/admin/admin_home.dart
  lib/src/admin/delete_module.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/login.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
  lib/src/authenticate/change_password.dart
  lib/src/authenticate/register_step1.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/notifications/tuteeNotifications/tutee_pending_requests.dart
  lib/src/notifications/tutorNotifications/tutor_notifications.dart
  lib/src/notifications/tutorNotifications/tutors_activity.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/home.dart
  lib/src/pages/tutor_explore.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/add_modules.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutor_page.dart
Labels: frontend, High, API

#363 💄 UI Colour scheme
  .env
  lib/screens/chat_screen.dart
  lib/screens/meeting_screen.dart
  lib/screens/recording_screen.dart
  lib/screens/startup_screen.dart
  lib/services/services/admin_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/admin/admin_home.dart
  lib/src/admin/delete_module.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
  lib/src/authenticate/register_step1.dart
  lib/src/pages/recorded_videos.dart
  lib/src/tutor_page.dart
  lib/src/widgets/chat_appbar_widget.dart
  lib/widgets/chat/chat_widget.dart
  lib/widgets/participant_grid_view/participant_tile.dart
  pubspec.yaml
Labels: enhancement, frontend, Low

#369 ✨ Recorded Videos
  .vscode/launch.json
  android/app/src/main/res/drawable-hdpi/tutorme.png
  android/app/src/main/res/drawable-mdpi/tutorme.png
  android/app/src/main/res/drawable-night-hdpi/tutorme.png
  android/app/src/main/res/drawable-night-mdpi/tutorme.png
  android/app/src/main/res/drawable-night-xhdpi/tutorme.png
  android/app/src/main/res/drawable-night-xxhdpi/tutorme.png
  android/app/src/main/res/drawable-night-xxxhdpi/tutorme.png
  android/app/src/main/res/drawable-xhdpi/tutorme.png
  android/app/src/main/res/drawable-xxhdpi/tutorme.png
  android/app/src/main/res/drawable-xxxhdpi/tutorme.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/drawable/tutorme.png
  lib/screens/recording_screen.dart
  lib/src/pages/recorded_videos.dart
Labels: enhancement, backend, frontend, Database, High, API

#375 Add baseURL and data persistance
  lib/main.dart
  lib/services/models/globals.dart
  lib/services/models/users.dart
  lib/services/services/admin_services.dart
  lib/services/services/group_services.dart
  lib/services/services/institution_services.dart
  lib/services/services/module_services.dart
  lib/services/services/user_services.dart
  lib/src/Groups/tutor_group.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register_step1.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/tutor_explore.dart
  lib/src/pages/tutors_list.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: frontend, High

#377 🚧 ✨ save recorded meetings
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-v21/launch_background.xml
  lib/screens/join_screen.dart
  lib/screens/meeting_screen.dart
  lib/screens/recording_screen.dart
  lib/screens/splash_screen.dart
  lib/screens/startup_screen.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/admin/delete_module.dart
  lib/src/admin/delete_tutee.dart
  lib/src/admin/delete_tutor.dart
  lib/src/admin/login.dart
  lib/src/admin/update_tutee.dart
  lib/src/admin/update_tutor.dart
  lib/src/pages/calls_page.dart
  lib/src/pages/recorded_videos.dart
Labels: enhancement, backend, frontend, High, Medium, API

#378 💄 (UI) - Added more screens and tabs
  assets/Pictures/about.jpg
  assets/Pictures/contactUs.jpg
  lib/services/models/event.dart
  lib/src/Navigation/about.dart
  lib/src/Navigation/contact_us.dart
  lib/src/Navigation/nav_settings.dart
  lib/src/Navigation/terms_and_conditions.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/register_step1.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
  lib/src/pages/booking_calendar.dart
  lib/src/pages/calendar.dart
  lib/src/pages/calendar_screen.dart
  lib/src/pages/home.dart
  lib/src/pages/invite_to_meeting.dart
  lib/src/pages/tutor_profile_booking_page.dart
Labels: enhancement, frontend

#379 Fixed frontend bugs
  lib/main.dart
  lib/services/models/globals.dart
  lib/services/services/group_services.dart
  lib/services/services/module_services.dart
  lib/services/services/user_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/landingPages/landing_page.dart
  lib/src/pages/home.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutor_page.dart
Labels: frontend

#380 💄Video Call UI
  .env
  lib/constants/colors.dart
  lib/screens/join_screen.dart
  lib/screens/meeting_screen.dart
  lib/services/services/group_services.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/pages/recorded_videos.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
  lib/widgets/meeting_controls/meeting_action_button.dart
Labels: enhancement, frontend, Medium

#382 Fixed fronted issues
  lib/services/services/admin_services.dart
  lib/services/services/group_services.dart
  lib/services/services/institution_services.dart
  lib/services/services/module_services.dart
  lib/services/services/user_services.dart
  lib/src/notifications/tutorNotifications/tutor_notifications.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/calendar.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/home.dart
  lib/src/pages/tutors_list.dart
  lib/src/pages/upcoming.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
Labels: frontend, High

#383 Fixed connections
  lib/services/services/user_services.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/pages/chats_page.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutor_page.dart
Labels: frontend, High

#389 Fixed frontend bugs
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.assets.cache
  lib/main.dart
  lib/services/services/user_services.dart
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/register_step2.dart
  lib/src/authenticate/register_step3.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
Labels: frontend

#390 🐛 (Frontend):Fixed multiple bugs
  android/app/build.gradle
  lib/services/services/module_services.dart
  lib/services/services/user_services.dart
  lib/src/notifications/tuteeNotifications/tutee_activity.dart
  lib/src/notifications/tuteeNotifications/tutee_notifications.dart
  lib/src/notifications/tuteeNotifications/tutee_pending_requests.dart
  lib/src/notifications/tutorNotifications/tutors_activity.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/home.dart
  lib/src/pages/text_recognition.dart
  lib/src/pages/tutors_list.dart
  lib/src/tuteeProfilePages/add_modules.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tutee_page.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  lib/src/tutor_page.dart
  pubspec.yaml
Labels: frontend

#392 ✨ One on one Chat
  APIs/TutorMeChatAPI/Chat application server/Hubs/ChatHub.cs
  assets/images/2.0x/flutter_logo.png
  assets/images/3.0x/flutter_logo.png
  assets/images/flutter_logo.png
  lib/src/chat/one_to_one_chat.dart
  windows/runner/resources/app_icon.ico
Labels: enhancement, backend, frontend, Database, High, API

#395 ✨ Review Tutor
  lib/src/admin/admin.dart
  lib/src/admin/review_tutor.dart
Labels: enhancement, backend, frontend, Database, High, API

#403 💄✨(BE integration to FE) Loaded calendar events and information from api
  lib/services/services/events_services.dart
  lib/services/services/user_services.dart
  lib/src/notifications/tutorNotifications/tutors_activity.dart
  lib/src/pages/calendar.dart
  lib/src/pages/calendar_screen.dart
  lib/src/pages/home.dart
  lib/src/pages/tutee_calendar_page.dart
  lib/src/pages/upcoming.dart
Labels: enhancement, frontend, API

#408 Added UI features
  lib/services/services/events_services.dart
  lib/services/services/group_services.dart
  lib/services/services/user_services.dart
  lib/src/notifications/tutorNotifications/tutors_requests.dart
  lib/src/pages/book_for_tutor.dart
  lib/src/pages/booking_calendar.dart
  lib/src/pages/invite_to_meeting.dart
  lib/src/pages/tutor_explore.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/pages/upcoming.dart
  lib/src/tuteeProfilePages/add_modules.dart
  lib/src/tuteeProfilePages/edit_module_list.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/home_tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
  lib/src/tutorVerifyShowcase/add_modules.dart
  lib/src/tutorVerifyShowcase/edit_module_list.dart
Labels: frontend

#411 ✨ Add and Delete Badges
  assets/Pictures/addBadge.png
  assets/Pictures/deleteBadge.png
  lib/services/services/admin_services.dart
  lib/src/admin/add_badge.dart
  lib/src/admin/admin.dart
  lib/src/admin/delete_badge.dart
  lib/src/admin/delete_user.dart
  lib/src/pages/recorded_videos.dart
Labels: enhancement, backend, frontend, Database, High, API

#415 Fixed transcripts
  .env
  lib/screens/join_screen.dart
  lib/screens/meeting_screen.dart
  lib/screens/startup_screen.dart
  lib/services/services/events_services.dart
  lib/services/services/group_services.dart
  lib/services/services/user_services.dart
  lib/src/Groups/add_tutees.dart
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
  lib/src/chat/booking_chat.dart
  lib/src/components.dart
  lib/src/pages/book_for_tutor.dart
  lib/src/tuteeProfilePages/tutee_profile_edit.dart
  lib/src/tutorProfilePages/pdfViewer/pdf_viewer.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_edit.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: frontend, High

#419 ✨ Verify Tutor
  lib/services/services/admin_services.dart
  lib/src/admin/review_tutor.dart
Labels: enhancement, backend, frontend, Database, High, API

#421 Added verification badge
  lib/services/services/user_services.dart
  lib/src/chat/one_to_one_chat.dart
  lib/src/pages/book_for_tutor.dart
  lib/src/pages/home.dart
  lib/src/pages/tutor_profile_booking_page.dart
  lib/src/tuteeProfilePages/tutee_profile.dart
  lib/src/tuteeProfilePages/tutee_profile_view.dart
  lib/src/tutorProfilePages/settings_pofile_view.dart
  lib/src/tutorProfilePages/tutor_profile_view.dart
  lib/src/tutorProfilePages/user_stats.dart
  lib/src/tutorVerifyShowcase/settings_pofile_view.dart
  lib/src/tutor_page.dart
Labels: frontend, Medium

#422 🐛 fixed bugs
  lib/src/Groups/tutee_group.dart
  lib/src/Groups/tutor_group.dart
Labels: frontend

#429 🙈 Gitignore
  .gitignore
Labels: enhancement, backend, High

#433 Modified UnitTests
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.GeneratedMSBuildEditorConfig.editorconfig
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/FileSystem.assets.cache
  APIs/FileSystemAPI/FileSystem/obj/Debug/net6.0/project.razor.json
  APIs/TutorMe/Tests/IntegrationTests/AuthorizationIntegrationTest.cs
  APIs/TutorMe/Tests/IntegrationTests/ConnectionsControllerIntegrationTests.cs
  APIs/TutorMe/Tests/IntegrationTests/GroupsControllerIntegrationTest.cs
  APIs/TutorMe/Tests/IntegrationTests/InstitutionsControllerIntegrationTest.cs
  APIs/TutorMe/Tests/IntegrationTests/ModulesControllerIntegrationTest.cs
  APIs/TutorMe/Tests/IntegrationTests/UserIntegrationTest.cs
  APIs/TutorMe/Tests/IntegrationTests/WebAppFactory.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/AccountControllerUnitTests.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/BadgesControllerUnitTest.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/ConnectionsControllerUnitTest.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/EventsControllerUnitTest.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/GroupVideosLinksControllerTest.cs
  APIs/TutorMe/Tests/UnitTests/ContronllerUnitTests/RequestControllerUnitTests.cs
  APIs/TutorMe/Tests/UnitTests/ServicesUnitTests/ConnectionServicesUnitTest.cs
  APIs/TutorMe/Tests/bin/Debug/net6.0/Tests.dll
  APIs/TutorMe/Tests/bin/Debug/net6.0/Tests.pdb
  APIs/TutorMe/Tests/bin/Debug/net6.0/TutorMe.dll
  APIs/TutorMe/Tests/bin/Debug/net6.0/TutorMe.pdb
  APIs/TutorMe/Tests/obj/Debug/net6.0/Tests.csproj.AssemblyReference.cache
  APIs/TutorMe/Tests/obj/Debug/net6.0/Tests.csproj.CoreCompileInputs.cache
  APIs/TutorMe/Tests/obj/Debug/net6.0/Tests.csproj.FileListAbsolute.txt
  APIs/TutorMe/Tests/obj/Debug/net6.0/Tests.dll
  APIs/TutorMe/Tests/obj/Debug/net6.0/Tests.pdb
  APIs/TutorMe/Tests/obj/Debug/net6.0/ref/Tests.dll
  APIs/TutorMe/Tests/obj/Debug/net6.0/refint/Tests.dll
  APIs/TutorMe/Tests/obj/rider.project.restore.info
  APIs/TutorMe/TutorMe.sln.DotSettings.user
  APIs/TutorMe/TutorMe/Controllers/AccountController.cs
  APIs/TutorMe/TutorMe/Controllers/BadgesController.cs
  APIs/TutorMe/TutorMe/Controllers/ConnectionsController.cs
  APIs/TutorMe/TutorMe/Services/ConnectionService.cs
  APIs/TutorMe/TutorMe/Services/EventService.cs
  APIs/TutorMe/TutorMe/Services/GroupVideosLinkService.cs
  APIs/TutorMe/TutorMe/TutorMe.csproj
  APIs/TutorMe/TutorMe/appsettings.json
  APIs/TutorMe/TutorMe/bin/Debug/net6.0/TutorMe.dll
  APIs/TutorMe/TutorMe/bin/Debug/net6.0/TutorMe.pdb
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.csproj.CoreCompileInputs.cache
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.csproj.FileListAbsolute.txt
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/TutorMe.pdb
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/ref/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/Debug/net6.0/refint/TutorMe.dll
  APIs/TutorMe/TutorMe/obj/rider.project.restore.info
  APIs/TutorMe/TutorMe/obj/staticwebassets.pack.sentinel
Labels: tests, backend, Database, High, API

#432 ✨ Super Admin User
  lib/services/services/admin_services.dart
  lib/services/services/user_services.dart
  lib/src/admin/delete_user.dart
Labels: enhancement, backend, Database, High, API

#440 Made final changes
  lib/src/pages/daily_usage.dart
  lib/src/pages/home.dart
  lib/src/pages/tutors_list.dart
  lib/src/pages/woah_factor.dart
  lib/src/pages/woah_factor_nav.dart
  pubspec.yaml
Labels: frontend

#442 Fixed bugs
  lib/src/Navigation/tutee_nav_drawer.dart
  lib/src/Navigation/tutor_nav_drawer.dart
  lib/src/admin/login.dart
  lib/src/admin/review_tutor.dart
  lib/src/authenticate/login.dart
  lib/src/pages/calendar_screen.dart
  lib/src/tutor_page.dart
Labels: frontend
