Repository COS301-SE-2022/Tutor-Me, pull requests merged in 2022-08, with the labels that each got.

#276 💄 Landing page
  lib/main.dart
  lib/src/tutorAndTuteeCollaboration/tuteeGroups/tutee_groups.dart
  lib/src/tutorAndTuteeCollaboration/tutorGroups/tutor_groups.dart
Labels: High

#278 💄 UI for Web
  .env
  lib/screens/chat_screen.dart
  lib/screens/meeting_screen.dart
  lib/src/authenticate/forgot_password.dart
  lib/src/authenticate/login.dart
  lib/src/authenticate/otp.dart
  lib/src/authenticate/register_step1.dart
  lib/src/theme/themes.dart
  lib/widgets/chat/chat_widget.dart
  lib/widgets/meeting_controls/meeting_action_bar.dart
  lib/widgets/participant_grid_view/participant_tile.dart
Labels: enhancement, good first issue, frontend, Low

#305 🌱 Update landing page
  assets/Pictures/undraw_Conference_re_2yld.png
  assets/Pictures/undraw_Visionary_technology_re_jfp7.png
  assets/Pictures/undraw_account_re_o7id.svg
  assets/Pictures/undraw_maker_launch_re_rq81.svg
  assets/Pictures/undraw_online_connection_6778.svg
  assets/Pictures/undraw_visionary_technology_re_jfp7.svg
  lib/main.dart
  lib/src/landingPages/landing_page.dart
Labels: frontend, Medium
